--------------------------------------------------------
--  File created - Tuesday-May-06-2025   
--------------------------------------------------------
DROP SEQUENCE EMPLOY�_SEQ;
DROP SEQUENCE EVT_SEQ;
DROP SEQUENCE LOCAL_SEQ;
DROP SEQUENCE LOCATAIRE_SEQ;
DROP SEQUENCE SEQ_PROJET_ID;
DROP TABLE EMPLOYE CASCADE CONSTRAINTS;
DROP TABLE EVT CASCADE CONSTRAINTS;
DROP TABLE LOCAL_COMMERCIALE CASCADE CONSTRAINTS;
DROP TABLE LOCATAIRES CASCADE CONSTRAINTS;
DROP TABLE MAINTENANCE CASCADE CONSTRAINTS;
DROP TABLE SERVICES CASCADE CONSTRAINTS;
--------------------------------------------------------
--  DDL for Sequence EMPLOY�_SEQ
--------------------------------------------------------

   CREATE SEQUENCE EMPLOY�_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence EVT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE EVT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE NOORDER NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence LOCAL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE LOCAL_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE NOORDER NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence LOCATAIRE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE LOCATAIRE_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE NOORDER NOCYCLE;
--------------------------------------------------------
--  DDL for Sequence SEQ_PROJET_ID
--------------------------------------------------------

   CREATE SEQUENCE SEQ_PROJET_ID MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE NOORDER NOCYCLE;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE EMPLOYE 
   (	ID_EMPLOYE NUMBER, 
	NOM VARCHAR2(20 BYTE), 
	DATE_E DATE, 
	POSTE VARCHAR2(30 BYTE), 
	SALAIRE FLOAT(126), 
	STATUS VARCHAR2(20 BYTE), 
	EMAIL VARCHAR2(30 BYTE), 
	ADRESSE VARCHAR2(20 BYTE), 
	PASSWORD VARCHAR2(128 BYTE), 
	ROLE VARCHAR2(20 BYTE), 
	PRENOM VARCHAR2(20 BYTE), 
	RFID VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM;
--------------------------------------------------------
--  DDL for Table EVT
--------------------------------------------------------

  CREATE TABLE EVT 
   (	ID_EVENEMENT NUMBER(*,0), 
	NOM VARCHAR2(255 BYTE), 
	DATE_EV DATE, 
	HEURE TIMESTAMP(6), 
	LIEU VARCHAR2(255 BYTE), 
	DESCRIPTION CLOB, 
	TYPE VARCHAR2(100 BYTE), 
	NUM_TEL VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM 
 LOB (DESCRIPTION) STORE AS BASICFILE (
  TABLESPACE SYSTEM ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT));
--------------------------------------------------------
--  DDL for Table LOCAL_COMMERCIALE
--------------------------------------------------------

  CREATE TABLE LOCAL_COMMERCIALE 
   (	ID_LOCAL NUMBER(20,0), 
	SURFACE FLOAT(126), 
	TYPE VARCHAR2(30 BYTE), 
	DISPONIBILITE VARCHAR2(30 BYTE), 
	PRIX FLOAT(126), 
	ETAGE VARCHAR2(20 BYTE), 
	ID_LOCATAIRE NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM;
--------------------------------------------------------
--  DDL for Table LOCATAIRES
--------------------------------------------------------

  CREATE TABLE LOCATAIRES 
   (	ID_LOCATAIRE NUMBER, 
	NOM VARCHAR2(20 BYTE), 
	ADRESSE VARCHAR2(20 BYTE), 
	EMAIL VARCHAR2(255 BYTE), 
	TELEPHONE NUMBER, 
	DEBUT_CONTRAT VARCHAR2(20 BYTE), 
	FIN_CONTRAT VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM;
--------------------------------------------------------
--  DDL for Table MAINTENANCE
--------------------------------------------------------

  CREATE TABLE MAINTENANCE 
   (	ID_MAINTENANCE NUMBER, 
	DESCRIPTION VARCHAR2(255 BYTE), 
	TYPE_MAINTENANCE VARCHAR2(255 BYTE), 
	CATEGORIE VARCHAR2(255 BYTE), 
	DATE_MAINTENANCE DATE, 
	STATUT VARCHAR2(255 BYTE), 
	ID_TECHNICIEN NUMBER, 
	EMAIL_TECHNICIEN VARCHAR2(255 BYTE), 
	NUMERO_TELEPHONE NUMBER, 
	ID_SERVICE NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM;
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE SERVICES 
   (	ID_SERVICE NUMBER, 
	NOM VARCHAR2(20 BYTE), 
	PRIX NUMBER, 
	DESCRIPTION VARCHAR2(255 BYTE), 
	STATUT CLOB, 
	TYPE VARCHAR2(20 BYTE), 
	DATEDEBUT DATE, 
	DATEFIN DATE, 
	DISTANCE FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM 
 LOB (STATUT) STORE AS BASICFILE (
  TABLESPACE SYSTEM ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT));
REM INSERTING into EMPLOYE
SET DEFINE OFF;
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (143,'NomInconnu',null,'PosteInconnu',null,'actif','aouadhi@gmail.com','AdresseInconnue','32616431633861643463333433393630356263646636396333376464343830663933313833376537636636356264333030353164363637393365623432376430','employe','PrenomInconnu',null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (123,'samar',to_date('02-04-25','DD-MM-RR'),'Responsable Employees',2800,'Actif',null,'bousalem rue omaine',null,'Responsable','aouadhi',null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (124,'sywar',to_date('02-04-25','DD-MM-RR'),'Responsable Evenements',3000,'Actif',null,'ariena centre ',null,'Responsable','aouadhiiiii',null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (125,'souhir',to_date('02-04-25','DD-MM-RR'),'Responsable Locataires',2900,'Actif',null,'bizert centre ',null,'Responsable','aouadhi',null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (858,'samar',to_date('12-05-65','DD-MM-RR'),'nhuuh',5252,'actif','nhjnhn','hybhb','251451','jjjn','aouadhi','A3478F28');
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (127,'jalila',to_date('02-04-25','DD-MM-RR'),'Responsable locaux comerciaux',6000,'Actif',null,'bousselm rue omaine',null,'Responsable','abidi',null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (128,'e',to_date('02-04-25','DD-MM-RR'),'Responsable Services',5000,'Actif',null,'bousselm rue omaine',null,'Responsable','m',null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (132,'hello',to_date('02-04-25','DD-MM-RR'),'Responsable Employees',2500,'Actif',null,'hellokitty1',null,'Responsable','hii',null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (133,'ggggggg',to_date('02-04-25','DD-MM-RR'),'Responsable Employees',2300,'Actif',null,'asedrtygfff',null,'Responsable','aaasssss',null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (135,'tytree',to_date('02-04-25','DD-MM-RR'),'Responsable Employees',2500,'Actif',null,'tredffrrnnnnn',null,'Responsable','treza',null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (3,'hxhsh',to_date('06-05-25','DD-MM-RR'),'Responsable Employees',2500,'Actif',null,'bousselm rue omaine',null,'Responsable','sjsj',null);
Insert into EMPLOYE (ID_EMPLOYE,NOM,DATE_E,POSTE,SALAIRE,STATUS,EMAIL,ADRESSE,PASSWORD,ROLE,PRENOM,RFID) values (5,'Boubakri',to_date('06-05-25','DD-MM-RR'),'Responsable Locataires',2700,'Actif',null,'bousselm rue omaine',null,'Responsable','ines',null);
REM INSERTING into EVT
SET DEFINE OFF;
Insert into EVT (ID_EVENEMENT,NOM,DATE_EV,HEURE,LIEU,TYPE,NUM_TEL) values (1,'jsjj',to_date('01-01-00','DD-MM-RR'),to_timestamp('01-05-25 00:00:00.000000000','DD-MM-RR HH24:MI:SSXFF'),'jdjdjdjd','sportif','+21653188371');
REM INSERTING into LOCAL_COMMERCIALE
SET DEFINE OFF;
Insert into LOCAL_COMMERCIALE (ID_LOCAL,SURFACE,TYPE,DISPONIBILITE,PRIX,ETAGE,ID_LOCATAIRE) values (1,1,'restaurant','dispo',5000,'1er etage',null);
REM INSERTING into LOCATAIRES
SET DEFINE OFF;
Insert into LOCATAIRES (ID_LOCATAIRE,NOM,ADRESSE,EMAIL,TELEPHONE,DEBUT_CONTRAT,FIN_CONTRAT) values (1,'ines','Rue Exemple','dupont@gmail.com',1234567,'2027-12-01','2028-12-30');
REM INSERTING into MAINTENANCE
SET DEFINE OFF;
Insert into MAINTENANCE (ID_MAINTENANCE,DESCRIPTION,TYPE_MAINTENANCE,CATEGORIE,DATE_MAINTENANCE,STATUT,ID_TECHNICIEN,EMAIL_TECHNICIEN,NUMERO_TELEPHONE,ID_SERVICE) values (12345678,'hxh  v vv v v v v v v vv v v ','jsjs','dhhd',to_date('06-05-25','DD-MM-RR'),'termin�',12345678,'dhdhdh@gmail.com',29116496,12345678);
REM INSERTING into SERVICES
SET DEFINE OFF;
Insert into SERVICES (ID_SERVICE,NOM,PRIX,DESCRIPTION,TYPE,DATEDEBUT,DATEFIN,DISTANCE) values (1,'shs',15,'bdbd','externe',to_date('01-01-00','DD-MM-RR'),to_date('01-01-02','DD-MM-RR'),null);
--------------------------------------------------------
--  DDL for Index EMPLOY�_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX EMPLOY�_PK ON EMPLOYE (ID_EMPLOYE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM;
--------------------------------------------------------
--  DDL for Trigger EMPLOYE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER EMPLOYE_TRG 
BEFORE INSERT ON EMPLOYE
FOR EACH ROW
BEGIN
    :NEW.ID_EMPLOYE := EMPLOY�_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER EMPLOYE_TRG ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOY�_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER EMPLOY�_TRG 
BEFORE INSERT ON EMPLOYE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER EMPLOY�_TRG ENABLE;
--------------------------------------------------------
--  DDL for Trigger EVT_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER EVT_ID_TRIGGER 
BEFORE INSERT ON EVT
FOR EACH ROW
BEGIN
    :NEW.ID_EVENEMENT := EVT_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER EVT_ID_TRIGGER ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCAL_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER LOCAL_ID_TRIGGER 
BEFORE INSERT ON LOCAL_COMMERCIALE
FOR EACH ROW
BEGIN
    :NEW.ID_LOCAL := LOCAL_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER LOCAL_ID_TRIGGER ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCATAIRE_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER LOCATAIRE_ID_TRIGGER 
BEFORE INSERT ON LOCATAIRES
FOR EACH ROW
BEGIN
    :NEW.ID_LOCATAIRE := LOCATAIRE_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER LOCATAIRE_ID_TRIGGER ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATAIRES
--------------------------------------------------------

  ALTER TABLE LOCATAIRES ADD PRIMARY KEY (ID_LOCATAIRE)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ENABLE;
  ALTER TABLE LOCATAIRES MODIFY (ID_LOCATAIRE NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCAL_COMMERCIALE
--------------------------------------------------------

  ALTER TABLE LOCAL_COMMERCIALE ADD PRIMARY KEY (ID_LOCAL)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ENABLE;
  ALTER TABLE LOCAL_COMMERCIALE MODIFY (ETAGE NOT NULL ENABLE);
  ALTER TABLE LOCAL_COMMERCIALE MODIFY (PRIX NOT NULL ENABLE);
  ALTER TABLE LOCAL_COMMERCIALE MODIFY (DISPONIBILITE NOT NULL ENABLE);
  ALTER TABLE LOCAL_COMMERCIALE MODIFY (TYPE NOT NULL ENABLE);
  ALTER TABLE LOCAL_COMMERCIALE MODIFY (SURFACE NOT NULL ENABLE);
  ALTER TABLE LOCAL_COMMERCIALE MODIFY (ID_LOCAL NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE SERVICES ADD PRIMARY KEY (ID_SERVICE)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ENABLE;
  ALTER TABLE SERVICES MODIFY (DATEFIN NOT NULL ENABLE);
  ALTER TABLE SERVICES MODIFY (DATEDEBUT NOT NULL ENABLE);
  ALTER TABLE SERVICES MODIFY (TYPE NOT NULL ENABLE);
  ALTER TABLE SERVICES MODIFY (STATUT NOT NULL ENABLE);
  ALTER TABLE SERVICES MODIFY (DESCRIPTION NOT NULL ENABLE);
  ALTER TABLE SERVICES MODIFY (PRIX NOT NULL ENABLE);
  ALTER TABLE SERVICES MODIFY (NOM NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVT
--------------------------------------------------------

  ALTER TABLE EVT ADD PRIMARY KEY (ID_EVENEMENT)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ENABLE;
  ALTER TABLE EVT MODIFY (LIEU NOT NULL ENABLE);
  ALTER TABLE EVT MODIFY (HEURE NOT NULL ENABLE);
  ALTER TABLE EVT MODIFY (DATE_EV NOT NULL ENABLE);
  ALTER TABLE EVT MODIFY (NOM NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAINTENANCE
--------------------------------------------------------

  ALTER TABLE MAINTENANCE ADD PRIMARY KEY (ID_MAINTENANCE)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ENABLE;
  ALTER TABLE MAINTENANCE MODIFY (ID_SERVICE NOT NULL ENABLE);
  ALTER TABLE MAINTENANCE MODIFY (NUMERO_TELEPHONE NOT NULL ENABLE);
  ALTER TABLE MAINTENANCE MODIFY (EMAIL_TECHNICIEN NOT NULL ENABLE);
  ALTER TABLE MAINTENANCE MODIFY (ID_TECHNICIEN NOT NULL ENABLE);
  ALTER TABLE MAINTENANCE MODIFY (STATUT NOT NULL ENABLE);
  ALTER TABLE MAINTENANCE MODIFY (DATE_MAINTENANCE NOT NULL ENABLE);
  ALTER TABLE MAINTENANCE MODIFY (CATEGORIE NOT NULL ENABLE);
  ALTER TABLE MAINTENANCE MODIFY (TYPE_MAINTENANCE NOT NULL ENABLE);
  ALTER TABLE MAINTENANCE MODIFY (DESCRIPTION NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE EMPLOYE ADD CONSTRAINT EMPLOY�_PK PRIMARY KEY (ID_EMPLOYE)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ENABLE;
  ALTER TABLE EMPLOYE MODIFY (NOM NOT NULL ENABLE);
  ALTER TABLE EMPLOYE MODIFY (POSTE NOT NULL ENABLE);
  ALTER TABLE EMPLOYE MODIFY (STATUS NOT NULL ENABLE);
  ALTER TABLE EMPLOYE MODIFY (ADRESSE NOT NULL ENABLE);
  ALTER TABLE EMPLOYE MODIFY (ROLE NOT NULL ENABLE);
  ALTER TABLE EMPLOYE MODIFY (PRENOM NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LOCAL_COMMERCIALE
--------------------------------------------------------

  ALTER TABLE LOCAL_COMMERCIALE ADD FOREIGN KEY (ID_LOCATAIRE)
	  REFERENCES LOCATAIRES (ID_LOCATAIRE) ENABLE;